# Generated by Django 5.0.2 on 2024-03-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/profile_image/'),
        ),
    ]
