# Generated by Django 5.0.2 on 2024-03-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0002_alter_userprofile_image'),
        ('connect_app', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
    ]
