# Generated by Django 5.0.2 on 2024-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0005_remove_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/default_cover.jpg', null=True, upload_to='images/cover_image/'),
        ),
    ]
